Algoritmo Promedio 

DEFINIR CAL1 COMO ENTERO
DEFINIR CAL2 COMO ENTERO 
DEFINIR PROM COMO ENTERO 
ESCRIBIR "INGRESA CALIFICACIÓN 1" 
LEER CAL1 
  
ESCRIBIR "INGRESA CALIFICACIÓN 2"
LEER CAL2

PROM=(CAL1+CAL2)/2

ESCRIBIR "TU CALIFICACIÓN ES: ", PROM

FinAlgoritmo 
